# Generated by Django 5.2 on 2025-04-07 20:41

import django.db.models.deletion
import events.models
import events.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome Settore')),
            ],
            options={
                'verbose_name': 'Settore',
                'verbose_name_plural': 'Settori',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[("Iniziative promozionali in Italia e all'estero", "Iniziative promozionali in Italia e all'estero"), ('Iniziative promozionali in loco', 'Iniziative promozionali in loco')], max_length=255, verbose_name='Categoria')),
                ('office', models.CharField(choices=[('Belgrado', 'Belgrado'), ('Podgorica', 'Podgorica')], max_length=50, verbose_name='Office')),
                ('titolo', models.CharField(max_length=255, verbose_name='Titolo')),
                ('data_inizio', models.DateField(verbose_name='Data Inizio')),
                ('data_fine', models.DateField(blank=True, null=True, verbose_name='Data Fine')),
                ('paese', models.CharField(choices=[('Italia', 'Italia'), ('Serbia', 'Serbia'), ('Montenegro', 'Montenegro'), ('Altro', 'Altro')], max_length=50, verbose_name='Paese')),
                ('citta', models.CharField(max_length=100, verbose_name='Città')),
                ('tipologia', models.CharField(max_length=255, verbose_name='Tipologia')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('privatistica', models.BooleanField(default=False, verbose_name='Privatistica')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aggiornamento')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_updated', to=settings.AUTH_USER_MODEL, verbose_name='Ultimo aggiornamento da')),
                ('settore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.settore', verbose_name='Settore')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
                'ordering': ['-data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, storage=events.storage.BackblazeB2Storage(), upload_to=events.models.get_upload_path, verbose_name='File')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo del file')),
                ('file_type', models.CharField(blank=True, choices=[('docx', 'Word Document'), ('pdf', 'PDF Document'), ('xlsx', 'Excel Spreadsheet')], max_length=10, verbose_name='Tipo di file')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data caricamento')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_files_created', to=settings.AUTH_USER_MODEL, verbose_name='Caricato da')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='events.event', verbose_name='Evento correlato')),
            ],
            options={
                'verbose_name': 'File Evento',
                'verbose_name_plural': 'File Eventi',
                'ordering': ['-created_at'],
            },
        ),
    ]
